kind: "Template"
apiVersion: "v1"
metadata:
  name: "pipeline"

parameters:
  - name: "GUID"
    displayName: "USers GUID"
    description: "The users GUID"
    required: true

  - name: "REPO"
    displayName: "Repository URL"
    description: "The repository URL where the Jenkinsfile is retrieved from"
    required: true

  - name: "SONAR_URL"
    displayName: "Sonarqube URLS"
    description: "The sonarqube url to be used"
    required: true

  - name: "NEXUS_RELEASE_URL"
    displayName: "Nexus release url"
    description: "The nexus release repositoryurl to deploy artifacts to"
    required: true

objects:
  - kind: "BuildConfig"
    apiVersion: "v1"
    metadata:
      name: "pipeline"
      labels:
        name: "pipeline"
        app: "jenkins"
    spec:
      source:
        type: "Git"
        contextDir: "openshift-tasks"
        git:
          uri: "${REPO}"
          ref: "master"
      strategy:
        jenkinsPipelineStrategy:
          env:
            - name: "GUID"
              value: "${GUID}"
            - name: "REPO"
              value: "${REPO}"
            - name: "SONAR_URL"
              value: "${SONAR_URL}"
            - name: "NEXUS_RELEASE_URL"
              value: "${NEXUS_RELEASE_URL}"
          jenkinsfilePath: Jenkinsfile